server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurante
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:

app:
  appDescription: "Pragma Powerup"
  appVersion: "1.0.0"

adapters:
  userfeignclient:
    url: http://localhost:8081